#If we list all the natural numbers below 10 that are multiples of $3$ or $5$, we get $3, 5, 6$ and $9$. The sum of these multiples is $23$.</p>
#Find the sum of all the multiples of $3$ or $5$ below 1000.



#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



#Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
#You may assume that each input would have exactly one solution, and you may not use the same element twice.
#You can return the answer in any order.


